apiVersion: v1
data:
  content.txt: |
    Hi! I got deployed in Kubernetes Base Environment using Kustomize
    Multi-line Test
kind: ConfigMap
metadata:
  name: go-api-content-configmap
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: go-api-service
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-api-label
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: go-api-app
  name: go-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-api-label
  template:
    metadata:
      labels:
        app: go-api-label
    spec:
      containers:
      - image: localhost/my-go-api-kustomize:1.0
        imagePullPolicy: IfNotPresent
        name: go-api-container
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /app/content
          name: go-api-content-file
      volumes:
      - configMap:
          name: go-api-content-configmap
        name: go-api-content-file
