apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../dev

images:
  - name: localhost/my-go-api-goclient
    newName: localhost:5000/my-go-api-goclient
    newTag: latest
