apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - configmap.yaml
  - service.yaml

images:
  - name: my-go-api-goclient
    newName: localhost/my-go-api-goclient
