apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: configmap-dev.yaml
  - path: service-dev.yaml

images:
  - name: my-go-api-goclient
    newName: localhost/my-go-api-goclient
    newTag: latest
